"""Apollo CLI - Command-line interface for Project LOGOS."""

from typing import Optional

import click
from rich.console import Console

console = Console()


@click.group()
@click.version_option(version="0.1.0", prog_name="apollo-cli")
def cli() -> None:
    """Apollo CLI - Command interface for Project LOGOS.

    Apollo provides a command-line interface for interacting with
    Sophia (the cognitive core), visualizing agent state, and
    monitoring plan execution.
    """
    pass


@cli.command()
def status() -> None:
    """Display current connection status."""
    console.print("[bold green]Apollo CLI v0.1.0[/bold green]")
    console.print("Status: Ready (infrastructure setup complete)")
    console.print(
        "\n[yellow]Note:[/yellow] Full integration with Sophia coming in Epoch 3"
    )


@cli.command()
def state() -> None:
    """Display current agent state."""
    console.print("[bold blue]Agent State[/bold blue]")
    console.print("State visualization will be implemented in Epoch 3 (Task C4)")
    console.print("\n[dim]This will show:[/dim]")
    console.print("  • Current world model state")
    console.print("  • Active plans and goals")
    console.print("  • Recent actions and outcomes")


@cli.command()
@click.argument("command", required=False)
def send(command: Optional[str]) -> None:
    """Send a command to Sophia cognitive core.

    Args:
        command: The command to send (optional for now)
    """
    if command:
        console.print(f"[bold]Command:[/bold] {command}")
        console.print(
            "[yellow]Command execution will be implemented in Epoch 3 (Task C4)[/yellow]"
        )
    else:
        console.print("[yellow]Usage:[/yellow] apollo-cli send '<your command>'")
        console.print("\n[dim]Example:[/dim] apollo-cli send 'pick up the red block'")


@cli.command()
@click.option("--recent", default=10, help="Number of recent plans to show")
def plans(recent: int) -> None:
    """Show recent plans generated by Sophia.

    Args:
        recent: Number of recent plans to display
    """
    console.print(f"[bold blue]Recent Plans[/bold blue] (last {recent})")
    console.print("Plan history will be implemented in Epoch 3 (Task C4)")


@cli.command()
def history() -> None:
    """Display command history."""
    console.print("[bold blue]Command History[/bold blue]")
    console.print("Command logging will be implemented in Epoch 3 (Task C4)")


def main() -> None:
    """Entry point for the CLI."""
    cli()


if __name__ == "__main__":
    main()
